"""
Minescript API data — scraped from https://minescript.net/docs
Used for autocomplete, documentation panel, and inline tooltips.
"""

# ── Data classes ───────────────────────────────────────────────────

class APIEntry:
    """One documented symbol (function, class, constant)."""
    __slots__ = ("name", "module", "signature", "description", "since", "category", "params", "returns")

    def __init__(self, name, module="minescript", signature="", description="",
                 since="", category="", params=None, returns=""):
        self.name = name
        self.module = module
        self.signature = signature
        self.description = description
        self.since = since
        self.category = category
        self.params = params or []
        self.returns = returns

    @property
    def completion_text(self) -> str:
        return self.name

    @property
    def detail_text(self) -> str:
        sig = f"({self.signature})" if self.signature else ""
        header = f"{self.module}.{self.name}{sig}"
        parts = [header, "", self.description]
        if self.params:
            parts.append("\nParameters:")
            for p in self.params:
                parts.append(f"  • {p}")
        if self.returns:
            parts.append(f"\nReturns: {self.returns}")
        if self.since:
            parts.append(f"\nSince: {self.since}")
        return "\n".join(parts)


# ── Minescript module functions ────────────────────────────────────

MINESCRIPT_API: list[APIEntry] = [
    # ── Output ─────────────────────────────────────────────────────
    APIEntry("execute", "minescript", "command: str",
             "Executes the given command. Backslash prefix = Minescript, otherwise Minecraft.",
             "v2.1", "commands"),
    APIEntry("echo", "minescript", "*messages",
             "Echoes plain-text messages to the chat. Visible only to local player.",
             "v2.0", "output"),
    APIEntry("echo_json", "minescript", "json_text",
             "Echoes JSON-formatted text to the chat. Visible only to local player.",
             "v4.0", "output"),
    APIEntry("chat", "minescript", "*messages",
             "Sends messages to the chat visible to all players.",
             "v2.0", "output"),
    APIEntry("log", "minescript", "*messages",
             "Sends messages to latest.log.",
             "v3.0", "output"),
    APIEntry("screenshot", "minescript", "filename: str = None",
             "Takes a screenshot, similar to pressing F2.",
             "v2.1", "output"),

    # ── Player info ────────────────────────────────────────────────
    APIEntry("player_name", "minescript", "",
             "Gets the local player's name.",
             "v2.1", "player", returns="str"),
    APIEntry("player_position", "minescript", "",
             "Gets the local player's position.",
             "v2.1", "player", returns="List[float] — [x, y, z]"),
    APIEntry("player_health", "minescript", "",
             "Gets the local player's health.",
             "v3.1", "player", returns="float"),
    APIEntry("player_orientation", "minescript", "",
             "Gets the local player's orientation.",
             "v2.1", "player", returns="[yaw: float, pitch: float]"),
    APIEntry("player_set_orientation", "minescript", "yaw: float, pitch: float",
             "Sets the local player's orientation.",
             "v2.1", "player",
             params=["yaw — degrees around y axis", "pitch — degrees from x-z plane"],
             returns="bool"),
    APIEntry("player_look_at", "minescript", "x: float, y: float, z: float",
             "Rotates the camera to look at a position.",
             "v4.0", "player"),
    APIEntry("player", "minescript", "*, nbt: bool = False",
             "Gets attributes for the local player.",
             "v4.0", "player", returns="EntityData"),
    APIEntry("players", "minescript",
             "*, nbt=False, uuid=None, name=None, position=None, offset=None, min_distance=None, max_distance=None, sort=None, limit=None",
             "Gets a list of nearby players and their attributes.",
             "v2.1", "player", returns="List[EntityData]"),
    APIEntry("player_hand_items", "minescript", "",
             "Gets the items in the local player's hands.",
             "v2.0", "player", returns="HandItems"),
    APIEntry("player_inventory", "minescript", "",
             "Gets the items in the local player's inventory.",
             "v2.0", "player", returns="List[ItemStack]"),
    APIEntry("player_inventory_select_slot", "minescript", "slot: int",
             "Selects the given slot within the player's hotbar.",
             "v3.0", "player",
             params=["slot — hotbar slot (0-8)"],
             returns="int — previously selected slot"),
    APIEntry("player_get_targeted_block", "minescript", "max_distance: float = 20",
             "Gets info about the nearest block in crosshairs.",
             "v3.0", "player", returns="TargetedBlock or None"),
    APIEntry("player_get_targeted_entity", "minescript", "max_distance: float = 20, nbt: bool = False",
             "Gets the entity targeted in crosshairs.",
             "v4.0", "player", returns="EntityData or None"),

    # ── Player movement ───────────────────────────────────────────
    APIEntry("player_press_forward", "minescript", "pressed: bool",
             "Starts/stops moving forward (simulates 'w' key).", "v2.1", "movement"),
    APIEntry("player_press_backward", "minescript", "pressed: bool",
             "Starts/stops moving backward (simulates 's' key).", "v2.1", "movement"),
    APIEntry("player_press_left", "minescript", "pressed: bool",
             "Starts/stops moving left (simulates 'a' key).", "v2.1", "movement"),
    APIEntry("player_press_right", "minescript", "pressed: bool",
             "Starts/stops moving right (simulates 'd' key).", "v2.1", "movement"),
    APIEntry("player_press_jump", "minescript", "pressed: bool",
             "Starts/stops jumping (simulates space key).", "v2.1", "movement"),
    APIEntry("player_press_sprint", "minescript", "pressed: bool",
             "Starts/stops sprinting (simulates left ctrl).", "v2.1", "movement"),
    APIEntry("player_press_sneak", "minescript", "pressed: bool",
             "Starts/stops sneaking (simulates left shift).", "v2.1", "movement"),
    APIEntry("player_press_pick_item", "minescript", "pressed: bool",
             "Starts/stops picking an item (simulates middle mouse).", "v2.1", "movement"),
    APIEntry("player_press_use", "minescript", "pressed: bool",
             "Starts/stops using an item (simulates right mouse).", "v2.1", "movement"),
    APIEntry("player_press_attack", "minescript", "pressed: bool",
             "Starts/stops attacking (simulates left mouse).", "v2.1", "movement"),
    APIEntry("player_press_swap_hands", "minescript", "pressed: bool",
             "Starts/stops swapping hands (simulates 'f' key).", "v2.1", "movement"),
    APIEntry("player_press_drop", "minescript", "pressed: bool",
             "Starts/stops dropping an item (simulates 'q' key).", "v2.1", "movement"),
    APIEntry("press_key_bind", "minescript", "key_mapping_name: str, pressed: bool",
             "Presses/unpresses a mapped key binding.",
             "v4.0", "movement",
             params=["key_mapping_name — e.g. 'key.attack', 'key.jump'", "pressed — True to press, False to release"]),

    # ── Entities ───────────────────────────────────────────────────
    APIEntry("entities", "minescript",
             "*, nbt=False, uuid=None, name=None, type=None, position=None, offset=None, min_distance=None, max_distance=None, sort=None, limit=None",
             "Gets a list of nearby entities and their attributes.",
             "v2.1", "entities", returns="List[EntityData]"),

    # ── World ──────────────────────────────────────────────────────
    APIEntry("world_info", "minescript", "",
             "Gets world properties (ticks, weather, spawn, difficulty, name, address).",
             "v4.0", "world", returns="WorldInfo"),
    APIEntry("version_info", "minescript", "",
             "Gets version info for Minecraft, Minescript, mod loader, launcher, OS.",
             "v4.0", "world", returns="VersionInfo"),

    # ── Blocks ─────────────────────────────────────────────────────
    APIEntry("getblock", "minescript", "x: int, y: int, z: int",
             "Gets the type of block at position (x, y, z).",
             "v2.0", "blocks", returns="str"),
    APIEntry("get_block", "minescript", "x: int, y: int, z: int",
             "Alias for getblock(...).", "v5.0", "blocks", returns="str"),
    APIEntry("getblocklist", "minescript", "positions: List[List[int]]",
             "Gets the types of block at the specified positions.",
             "v2.1", "blocks", returns="List[str]"),
    APIEntry("get_block_list", "minescript", "positions: List[List[int]]",
             "Alias for getblocklist(...).", "v5.0", "blocks", returns="List[str]"),
    APIEntry("get_block_region", "minescript", "pos1: BlockPos, pos2: BlockPos, safety_limit: bool = True",
             "Gets the types of blocks in an axis-aligned bounding box.",
             "v5.0", "blocks", returns="BlockRegion"),
    APIEntry("await_loaded_region", "minescript", "x1: int, z1: int, x2: int, z2: int",
             "Waits for chunks to load in the region from (x1,z1) to (x2,z2).",
             "v2.1", "blocks"),

    # ── Jobs ───────────────────────────────────────────────────────
    APIEntry("job_info", "minescript", "",
             "Return info about active Minescript jobs.",
             "v4.0", "jobs", returns="List[JobInfo]"),
    APIEntry("flush", "minescript", "",
             "Wait for all previously issued script commands to complete.",
             "v2.1", "jobs"),
    APIEntry("set_default_executor", "minescript", "executor",
             "Sets the default executor for script functions (tick_loop, render_loop, script_loop).",
             "v4.0", "jobs"),

    # ── Screen / Chat ─────────────────────────────────────────────
    APIEntry("screen_name", "minescript", "",
             "Gets the current GUI screen name, if there is one.",
             "v3.2", "screen", returns="str or None"),
    APIEntry("show_chat_screen", "minescript", "show: bool, prompt: str = None",
             "Shows or hides the chat screen.",
             "v4.0", "screen", returns="bool"),
    APIEntry("append_chat_history", "minescript", "message: str",
             "Appends message to chat history.", "v4.0", "screen"),
    APIEntry("chat_input", "minescript", "",
             "Gets state of chat input text.", "v4.0", "screen",
             returns="[text: str, position: int]"),
    APIEntry("set_chat_input", "minescript", "text=None, position=None, color=None",
             "Sets state of chat input text.", "v4.0", "screen"),
    APIEntry("container_get_items", "minescript", "",
             "Gets all items in an open container (chest, furnace, etc).",
             "v4.0", "screen", returns="List[ItemStack] or None"),

    # ── Events ─────────────────────────────────────────────────────
    APIEntry("EventQueue", "minescript", "",
             "Queue for managing events. Use with 'with' statement for auto-unregister.",
             "v4.0", "events"),
    APIEntry("add_event_listener", "minescript", "event_type: str, callback, **args",
             "Adds an event listener. Pyjinn only.",
             "v4.0", "events", returns="int — listener ID"),
    APIEntry("remove_event_listener", "minescript", "listener_id: int",
             "Removes an event listener. Pyjinn only.",
             "v4.0", "events", returns="bool"),
    APIEntry("set_timeout", "minescript", "callback, timer_millis: int, *args, **kwargs",
             "Schedules callback once after timer_millis ms. Pyjinn only.",
             "v4.0", "events", returns="int — callback ID"),
    APIEntry("set_interval", "minescript", "callback, timer_millis: int, *args, **kwargs",
             "Schedules callback every timer_millis ms. Pyjinn only.",
             "v4.0", "events", returns="int — callback ID"),

    # ── BlockPack / BlockPacker ────────────────────────────────────
    APIEntry("BlockPack", "minescript", "",
             "Immutable, serializable collection of blocks. Read/write worlds, files, bytes.",
             "v3.0", "blockpack"),
    APIEntry("BlockPack.read_world", "minescript",
             "pos1, pos2, *, rotation=None, offset=None, comments={}, safety_limit=True",
             "Creates a blockpack from blocks in the world.",
             "v3.0", "blockpack", returns="BlockPack"),
    APIEntry("BlockPack.read_file", "minescript", "filename: str, *, relative_to_cwd=False",
             "Reads a blockpack from a file.", "v3.0", "blockpack", returns="BlockPack"),
    APIEntry("BlockPack.write_world", "minescript", "*, rotation=None, offset=None",
             "Writes blocks from this BlockPack into the current world.", "v3.0", "blockpack"),
    APIEntry("BlockPack.write_file", "minescript", "filename: str, *, relative_to_cwd=False",
             "Writes this BlockPack to a file.", "v3.0", "blockpack"),
    APIEntry("BlockPack.export_data", "minescript", "",
             "Serializes this BlockPack into a base64-encoded string.", "v3.0", "blockpack", returns="str"),
    APIEntry("BlockPack.import_data", "minescript", "base64_data: str",
             "Creates a blockpack from base64-encoded data.", "v3.0", "blockpack", returns="BlockPack"),
    APIEntry("BlockPacker", "minescript", "",
             "Mutable collection of blocks. Use setblock/fill, then pack() to create BlockPack.",
             "v3.0", "blockpack"),
    APIEntry("BlockPacker.setblock", "minescript", "pos: BlockPos, block_type: str",
             "Sets a block within this BlockPacker.", "v3.0", "blockpack"),
    APIEntry("BlockPacker.fill", "minescript", "pos1: BlockPos, pos2: BlockPos, block_type: str",
             "Fills blocks within this BlockPacker.", "v3.0", "blockpack"),
    APIEntry("BlockPacker.pack", "minescript", "*, comments: Dict[str, str] = {}",
             "Packs blocks into a new BlockPack.", "v3.0", "blockpack", returns="BlockPack"),

    # ── Java interop ───────────────────────────────────────────────
    APIEntry("java_class", "minescript", "name: str",
             "Looks up Java class by fully qualified name.", "v4.0", "java", returns="JavaHandle"),
    APIEntry("java_string", "minescript", "s: str",
             "Returns handle to a Java String.", "v4.0", "java", returns="JavaHandle"),
    APIEntry("java_int", "minescript", "i: int",
             "Returns handle to a Java Integer.", "v4.0", "java", returns="JavaHandle"),
    APIEntry("java_float", "minescript", "f: float",
             "Returns handle to a Java Float.", "v4.0", "java", returns="JavaHandle"),
    APIEntry("java_double", "minescript", "d: float",
             "Returns handle to a Java Double.", "v4.0", "java", returns="JavaHandle"),
    APIEntry("java_long", "minescript", "l: int",
             "Returns handle to a Java Long.", "v4.0", "java", returns="JavaHandle"),
    APIEntry("java_bool", "minescript", "b: bool",
             "Returns handle to a Java Boolean.", "v4.0", "java", returns="JavaHandle"),
    APIEntry("java_member", "minescript", "clazz: JavaHandle, name: str",
             "Gets Java member(s) matching name.", "v4.0", "java", returns="JavaHandle"),
    APIEntry("java_access_field", "minescript", "target: JavaHandle, field: JavaHandle",
             "Accesses a field on a target Java object.", "v4.0", "java", returns="JavaHandle or None"),
    APIEntry("java_call_method", "minescript", "target: JavaHandle, method: JavaHandle, *args",
             "Invokes a method on a target Java object.", "v4.0", "java", returns="JavaHandle or None"),
    APIEntry("java_new_instance", "minescript", "ctor: JavaHandle, *args",
             "Creates new Java instance.", "v4.0", "java", returns="JavaHandle"),
    APIEntry("java_ctor", "minescript", "clazz: JavaHandle",
             "Returns handle to a constructor set for the given class.", "v4.0", "java", returns="JavaHandle"),
    APIEntry("java_to_string", "minescript", "target: JavaHandle",
             "Returns Python string from target.toString() in Java.", "v4.0", "java", returns="str"),
    APIEntry("java_release", "minescript", "*targets",
             "Releases Java reference(s).", "v4.0", "java"),
    APIEntry("java_array_length", "minescript", "array: JavaHandle",
             "Returns length of Java array.", "v4.0", "java", returns="int"),
    APIEntry("java_array_index", "minescript", "array: JavaHandle, i: int",
             "Gets indexed element of Java array.", "v4.0", "java", returns="JavaHandle or None"),
    APIEntry("java_new_array", "minescript", "element_type: JavaHandle, *elements",
             "Creates a new Java array.", "v5.0", "java", returns="JavaHandle"),
    APIEntry("java_assign", "minescript", "dest: JavaHandle, source: JavaHandle",
             "Reassigns dest to reference the object referenced by source.", "v4.0", "java"),
    APIEntry("java_field_names", "minescript", "clazz: JavaHandle",
             "Returns list of field names for the class.", "v5.0", "java", returns="List[str]"),
    APIEntry("java_method_names", "minescript", "clazz: JavaHandle",
             "Returns list of method names for the class.", "v5.0", "java", returns="List[str]"),
    APIEntry("java_call_script_function", "minescript", "func_name, *args",
             "Calls the requested script function with Java params.", "v4.0", "java", returns="JavaHandle"),

    # ── Pyjinn ─────────────────────────────────────────────────────
    APIEntry("eval_pyjinn_script", "java", "script_code: str",
             "Creates a Pyjinn script given source code as a string.", "v5.0", "pyjinn", returns="JavaObject"),
    APIEntry("import_pyjinn_script", "java", "pyj_filename: str",
             "Imports a Pyjinn script from a .pyj file.", "v5.0", "pyjinn", returns="JavaObject"),

    # ── MinescriptPlus — Inventory ─────────────────────────────────
    APIEntry("Inventory.click_slot", "minescript_plus",
             "slot: int, right_button: bool = False",
             "Click on a slot in the inventory or open container.",
             "v0.13+", "ms_plus_inv", returns="bool"),
    APIEntry("Inventory.shift_click_slot", "minescript_plus",
             "slot: int",
             "Shift-click a slot (quick-move item).",
             "v0.13+", "ms_plus_inv", returns="bool"),
    APIEntry("Inventory.inventory_hotbar_swap", "minescript_plus",
             "inv_slot: int, hotbar_slot: int",
             "Swap an inventory slot with a hotbar slot.",
             "v0.13+", "ms_plus_inv", returns="bool"),
    APIEntry("Inventory.open_targeted_chest", "minescript_plus",
             "",
             "Open the chest/container the player is looking at.",
             "v0.13+", "ms_plus_inv", returns="bool"),
    APIEntry("Inventory.take_items", "minescript_plus",
             "slots: list[int]",
             "Take items from the given slots.",
             "v0.13+", "ms_plus_inv", returns="bool"),
    APIEntry("Inventory.find_item", "minescript_plus",
             "item_id: str, cust_name: str, container: bool, try_open: bool",
             "Find an item by ID/name in inventory or container.",
             "v0.13+", "ms_plus_inv", returns="int | None"),

    # ── MinescriptPlus — Screen & GUI ─────────────────────────────
    APIEntry("Screen.wait_screen", "minescript_plus",
             "name: str, delay: int",
             "Wait until a specific screen is open.",
             "v0.13+", "ms_plus_gui", returns="bool"),
    APIEntry("Screen.close_screen", "minescript_plus",
             "",
             "Close the currently open screen.",
             "v0.13+", "ms_plus_gui"),
    APIEntry("Gui.get_title", "minescript_plus", "",
             "Get the current title text.", "v0.13+", "ms_plus_gui", returns="str | None"),
    APIEntry("Gui.get_subtitle", "minescript_plus", "",
             "Get the current subtitle text.", "v0.13+", "ms_plus_gui", returns="str | None"),
    APIEntry("Gui.get_actionbar", "minescript_plus", "",
             "Get the current actionbar text.", "v0.13+", "ms_plus_gui", returns="str | None"),
    APIEntry("Gui.set_title", "minescript_plus", "text: str",
             "Set the title overlay text.", "v0.13+", "ms_plus_gui"),
    APIEntry("Gui.set_subtitle", "minescript_plus", "text: str",
             "Set the subtitle overlay text.", "v0.13+", "ms_plus_gui"),
    APIEntry("Gui.set_actionbar", "minescript_plus", "text: str, tinted: bool",
             "Set the actionbar text.", "v0.13+", "ms_plus_gui"),
    APIEntry("Gui.set_title_times", "minescript_plus",
             "fadeInTicks: int, stayTicks: int, fadeOutTicks: int",
             "Set the fade-in, stay, and fade-out times for titles.",
             "v0.13+", "ms_plus_gui"),
    APIEntry("Gui.reset_title_times", "minescript_plus", "",
             "Reset title display times to defaults.", "v0.13+", "ms_plus_gui"),
    APIEntry("Gui.clear_titles", "minescript_plus", "",
             "Clear all currently displayed titles.", "v0.13+", "ms_plus_gui"),

    # ── MinescriptPlus — Key & Client ─────────────────────────────
    APIEntry("Key.press_key", "minescript_plus",
             "key_name: str, state: bool",
             "Simulate pressing or releasing a keyboard key.",
             "v0.13+", "ms_plus_client"),
    APIEntry("Client.pause_game", "minescript_plus", "",
             "Pause the game.", "v0.13+", "ms_plus_client", returns="bool"),
    APIEntry("Client.disconnect", "minescript_plus", "",
             "Disconnect from the current server.", "v0.13+", "ms_plus_client"),
    APIEntry("Client.is_local_server", "minescript_plus", "",
             "Check if the client is connected to a local server.",
             "v0.13+", "ms_plus_client", returns="bool"),
    APIEntry("Client.is_multiplayer_server", "minescript_plus", "",
             "Check if the client is connected to a multiplayer server.",
             "v0.13+", "ms_plus_client", returns="bool"),
    APIEntry("Client.get_options", "minescript_plus", "",
             "Get the Minecraft game options object.",
             "v0.13+", "ms_plus_client", returns="GameOptions"),

    # ── MinescriptPlus — Player ────────────────────────────────────
    APIEntry("Player.get_latency", "minescript_plus", "",
             "Get the player's network latency in ms.",
             "v0.13+", "ms_plus_player", returns="int"),
    APIEntry("Player.get_game_mode", "minescript_plus", "",
             "Get the player's current game mode.",
             "v0.13+", "ms_plus_player", returns="str"),
    APIEntry("Player.is_creative", "minescript_plus", "",
             "Check if the player is in Creative mode.",
             "v0.13+", "ms_plus_player", returns="bool"),
    APIEntry("Player.is_survival", "minescript_plus", "",
             "Check if the player is in Survival mode.",
             "v0.13+", "ms_plus_player", returns="bool"),
    APIEntry("Player.get_skin_url", "minescript_plus", "",
             "Get the URL of the player's skin texture.",
             "v0.13+", "ms_plus_player", returns="str"),
    APIEntry("Player.get_food_level", "minescript_plus", "",
             "Get the player's current food level.",
             "v0.13+", "ms_plus_player", returns="float"),
    APIEntry("Player.get_saturation_level", "minescript_plus", "",
             "Get the player's saturation level.",
             "v0.13+", "ms_plus_player", returns="float"),
    APIEntry("Player.get_player_block_position", "minescript_plus", "",
             "Get the player's position as block coordinates.",
             "v0.13+", "ms_plus_player", returns="list[int]"),
    APIEntry("Player.get_xp_levels", "minescript_plus", "",
             "Get the player's XP level count.",
             "v0.13+", "ms_plus_player", returns="int"),
    APIEntry("Player.get_experience_progress", "minescript_plus", "",
             "Get the player's experience progress (0.0 – 1.0).",
             "v0.13+", "ms_plus_player", returns="float"),

    # ── MinescriptPlus — Server ────────────────────────────────────
    APIEntry("Server.is_local", "minescript_plus", "",
             "Check if connected to a local/singleplayer server.",
             "v0.13+", "ms_plus_server", returns="bool"),
    APIEntry("Server.get_ping", "minescript_plus", "",
             "Get the current server ping in ms.",
             "v0.13+", "ms_plus_server", returns="int | None"),
    APIEntry("Server.is_lan", "minescript_plus", "",
             "Check if connected to a LAN server.",
             "v0.13+", "ms_plus_server", returns="bool | None"),
    APIEntry("Server.is_realm", "minescript_plus", "",
             "Check if connected to a Realm.",
             "v0.13+", "ms_plus_server", returns="bool | None"),
    APIEntry("Server.get_tablist", "minescript_plus", "",
             "Get the tab list entries.",
             "v0.13+", "ms_plus_server", returns="list"),

    # ── MinescriptPlus — World ─────────────────────────────────────
    APIEntry("World.is_raining", "minescript_plus", "",
             "Check if it's raining.", "v0.13+", "ms_plus_world", returns="bool"),
    APIEntry("World.is_thundering", "minescript_plus", "",
             "Check if it's thundering.", "v0.13+", "ms_plus_world", returns="bool"),
    APIEntry("World.is_hardcore", "minescript_plus", "",
             "Check if the world is hardcore.", "v0.13+", "ms_plus_world", returns="bool"),
    APIEntry("World.get_difficulty", "minescript_plus", "",
             "Get the current difficulty.", "v0.13+", "ms_plus_world"),
    APIEntry("World.get_spawn_pos", "minescript_plus", "",
             "Get the world spawn position.", "v0.13+", "ms_plus_world"),
    APIEntry("World.get_game_time", "minescript_plus", "",
             "Get the total game time in ticks.", "v0.13+", "ms_plus_world", returns="int"),
    APIEntry("World.get_day_time", "minescript_plus", "",
             "Get the current day time in ticks.", "v0.13+", "ms_plus_world", returns="int"),
    APIEntry("World.get_sign_text", "minescript_plus",
             "x: int = None, y: int = None, z: int = None",
             "Read text from a sign at the given position.",
             "v0.13+", "ms_plus_world", returns="list[str] | None"),
    APIEntry("World.set_sign_text", "minescript_plus",
             "text: list[str], x: int = None, y: int = None, z: int = None, is_front: bool = None",
             "Set text on a sign at the given position.",
             "v0.13+", "ms_plus_world", returns="bool"),
    APIEntry("World.find_nearest_entity", "minescript_plus",
             "name_str: str = '', type_str: str = ''",
             "Find the nearest entity matching name/type.",
             "v0.13+", "ms_plus_world", returns="EntityData | None"),
    APIEntry("World.get_destroy_progress", "minescript_plus", "",
             "Get the current block-breaking progress (0.0 – 1.0).",
             "v0.13+", "ms_plus_world", returns="float"),
    APIEntry("World.get_destroy_stage", "minescript_plus", "",
             "Get the current block-breaking stage (0 – 9).",
             "v0.13+", "ms_plus_world", returns="int"),

    # ── MinescriptPlus — Trading ───────────────────────────────────
    APIEntry("Trading.get_offers", "minescript_plus", "",
             "Get all available villager trade offers.",
             "v0.13+", "ms_plus_trading"),
    APIEntry("Trading.get_offer", "minescript_plus", "offer_index: int",
             "Get a specific trade offer by index.",
             "v0.13+", "ms_plus_trading"),
    APIEntry("Trading.get_costA", "minescript_plus", "offer_index: int",
             "Get the first cost item for a trade.",
             "v0.13+", "ms_plus_trading"),
    APIEntry("Trading.get_costB", "minescript_plus", "offer_index: int",
             "Get the second cost item for a trade.",
             "v0.13+", "ms_plus_trading"),
    APIEntry("Trading.get_result", "minescript_plus", "offer_index: int",
             "Get the result item for a trade.",
             "v0.13+", "ms_plus_trading"),
    APIEntry("Trading.trade_offer", "minescript_plus", "offer_index: int",
             "Execute a trade at the given index.",
             "v0.13+", "ms_plus_trading", returns="bool"),

    # ── MinescriptPlus — HUD ──────────────────────────────────────
    APIEntry("Hud.add_text", "minescript_plus",
             "text: str, x: int, y: int, color: tuple = (255,255,255), alpha: int = 255, scale: float = 1.0, shadow: bool = False, ...",
             "Add a persistent HUD text element. (Requires Fabric API.)",
             "v0.13+", "ms_plus_hud", returns="int — element index"),
    APIEntry("Hud.update_text", "minescript_plus",
             "index: int, text: str, x: int, y: int, ...",
             "Update an existing HUD text element.",
             "v0.13+", "ms_plus_hud"),
    APIEntry("Hud.remove_text", "minescript_plus", "index: int",
             "Remove a HUD text element.", "v0.13+", "ms_plus_hud"),
    APIEntry("Hud.clear_texts", "minescript_plus", "",
             "Remove all HUD text elements.", "v0.13+", "ms_plus_hud"),
    APIEntry("Hud.add_item", "minescript_plus",
             "item_id: str, x: int, y: int, count: str = '', scale: float = 1.0, ...",
             "Add a HUD item icon element.",
             "v0.13+", "ms_plus_hud", returns="int — element index"),
    APIEntry("Hud.update_item", "minescript_plus", "index: int, ...",
             "Update a HUD item element.", "v0.13+", "ms_plus_hud"),
    APIEntry("Hud.remove_item", "minescript_plus", "index: int",
             "Remove a HUD item element.", "v0.13+", "ms_plus_hud"),
    APIEntry("Hud.clear_items", "minescript_plus", "",
             "Remove all HUD item elements.", "v0.13+", "ms_plus_hud"),
    APIEntry("Hud.show_hud", "minescript_plus", "enable: bool",
             "Show or hide the entire HUD overlay.", "v0.13+", "ms_plus_hud"),
    APIEntry("Hud.show_text", "minescript_plus", "index: int, enable: bool",
             "Show or hide a specific HUD text element.", "v0.13+", "ms_plus_hud"),
    APIEntry("Hud.show_item", "minescript_plus", "index: int, enable: bool",
             "Show or hide a specific HUD item element.", "v0.13+", "ms_plus_hud"),

    # ── MinescriptPlus — Utility ──────────────────────────────────
    APIEntry("Util.get_job_id", "minescript_plus", "cmd: str",
             "Get the job ID for a running Minescript command.",
             "v0.13+", "ms_plus_util", returns="int | None"),
    APIEntry("Util.get_clipboard", "minescript_plus", "",
             "Get the system clipboard text.",
             "v0.13+", "ms_plus_util", returns="str"),
    APIEntry("Util.set_clipboard", "minescript_plus", "string: str",
             "Set the system clipboard text.",
             "v0.13+", "ms_plus_util"),
    APIEntry("Util.get_distance", "minescript_plus",
             "pos1: list, pos2: list | None = None",
             "Get the distance between two positions (or from the player).",
             "v0.13+", "ms_plus_util", returns="float"),
    APIEntry("Util.get_nbt", "minescript_plus", "obj: dict, path: str, default = None",
             "Get a value from an NBT dict by dot-separated path.",
             "v0.13+", "ms_plus_util", returns="Any"),
    APIEntry("Util.get_light_level", "minescript_plus",
             "block_pos = None, source: str = 'RAW'",
             "Get the light level at a position. Source: RAW, SKY, BLOCK.",
             "v0.13+", "ms_plus_util", returns="int"),
    APIEntry("Util.play_sound", "minescript_plus",
             "sound = None, sound_source = None, volume: float = 1.0, pitch: float = 1.0",
             "Play a sound at the player's position.",
             "v0.13+", "ms_plus_util"),
    APIEntry("Util.get_soundevents", "minescript_plus", "",
             "Get all available sound event names.",
             "v0.13+", "ms_plus_util"),
    APIEntry("Util.get_soundsource", "minescript_plus", "",
             "Get all available sound source names.",
             "v0.13+", "ms_plus_util"),
    APIEntry("Util.show_toast", "minescript_plus", "",
             "Show a system toast notification.", "v0.13+", "ms_plus_util"),

    # ── MinescriptPlus — Keybind & Events ─────────────────────────
    APIEntry("Keybind.set_keybind", "minescript_plus",
             "key: int, callback, name: str = '', category: str = '', description: str = ''",
             "Register a custom keybind with a callback function.",
             "v0.13+", "ms_plus_events"),
    APIEntry("Keybind.modify_keybind", "minescript_plus",
             "key: int, callback, name: str = '', category: str = '', description: str = ''",
             "Modify an existing keybind.",
             "v0.13+", "ms_plus_events"),
    APIEntry("Keybind.remove_keybind", "minescript_plus", "key: int",
             "Remove a registered keybind.",
             "v0.13+", "ms_plus_events"),
    APIEntry("Event.register", "minescript_plus",
             "event_name: str, callback, once: bool = False, check_interval: float = 0.05",
             "Register an event listener (on_title, on_subtitle, on_actionbar, on_open_screen).",
             "v0.13+", "ms_plus_events", returns="Listener"),
    APIEntry("Event.unregister", "minescript_plus", "listener: Listener",
             "Unregister an event listener.", "v0.13+", "ms_plus_events"),
    APIEntry("input", "minescript_plus",
             "prompt: str = '', save_history: bool = False",
             "Read input from Minecraft chat. Replacement for Python's built-in input().",
             "v0.13+", "ms_plus_util", returns="str"),
]

# ── Data types / structs ───────────────────────────────────────────

MINESCRIPT_TYPES: list[APIEntry] = [
    APIEntry("BlockPos", "minescript", "", "Tuple (x: int, y: int, z: int) position in block space.", "", "types"),
    APIEntry("Vector3f", "minescript", "", "Tuple (x: float, y: float, z: float) position or offset.", "", "types"),
    APIEntry("JobInfo", "minescript", "",
             "job_id: int, command: List[str], source: str, status: str, parent_job_id: int|None, self: bool",
             "v4.0", "types"),
    APIEntry("ItemStack", "minescript", "",
             "item: str, count: int, nbt: str = None, slot: int = None, selected: bool = None",
             "", "types"),
    APIEntry("HandItems", "minescript", "",
             "main_hand: ItemStack, off_hand: ItemStack", "", "types"),
    APIEntry("EntityData", "minescript", "",
             "name, type, uuid, id, position, yaw, pitch, velocity, lerp_position, health, local, passengers, nbt",
             "", "types"),
    APIEntry("TargetedBlock", "minescript", "",
             "position: BlockPos, distance: float, side: str, type: str", "", "types"),
    APIEntry("VersionInfo", "minescript", "",
             "minecraft, minescript, mod_loader, launcher, os_name, os_version, minecraft_class_name, pyjinn",
             "v4.0", "types"),
    APIEntry("WorldInfo", "minescript", "",
             "game_ticks, day_ticks, raining, thundering, spawn, hardcore, difficulty, name, address",
             "v4.0", "types"),
    APIEntry("KeyEvent", "minescript", "",
             "type, time, key, scan_code, action (0=up, 1=down, 2=repeat), modifiers, screen",
             "", "types"),
    APIEntry("MouseEvent", "minescript", "",
             "type, time, button, action (0=up, 1=down), modifiers, x, y, screen",
             "", "types"),
    APIEntry("ChatEvent", "minescript", "", "type, time, message", "", "types"),
    APIEntry("AddEntityEvent", "minescript", "", "type, time, entity: EntityData", "", "types"),
    APIEntry("BlockUpdateEvent", "minescript", "", "type, time, position, old_state, new_state", "", "types"),
    APIEntry("TakeItemEvent", "minescript", "", "type, time, player_uuid, item, amount", "", "types"),
    APIEntry("DamageEvent", "minescript", "", "type, time, entity_uuid, cause_uuid, source", "", "types"),
    APIEntry("ExplosionEvent", "minescript", "", "type, time, position, blockpack_base64", "", "types"),
    APIEntry("ChunkEvent", "minescript", "", "type, time, loaded, x_min, z_min, x_max, z_max", "", "types"),
    APIEntry("WorldEvent", "minescript", "", "type, time, connected", "v5.0", "types"),
    APIEntry("BlockRegion", "minescript", "",
             "Accessor for blocks within an axis-aligned bounding box.", "v5.0", "types"),
    APIEntry("Rotations", "minescript", "",
             "Common rotations: IDENTITY, X_90, X_180, X_270, Y_90, Y_180, Y_270, Z_90, Z_180, Z_270, INVERT_X, INVERT_Y, INVERT_Z",
             "v3.0", "types"),
    APIEntry("BlockPack", "minescript", "",
             "Immutable, serializable collection of blocks.", "v3.0", "types"),
    APIEntry("BlockPacker", "minescript", "",
             "Mutable collection of blocks.", "v3.0", "types"),
    APIEntry("EventQueue", "minescript", "",
             "Queue for managing events with context manager support.", "v4.0", "types"),
    APIEntry("MinescriptRuntimeOptions", "minescript", "",
             "legacy_dict_return_values: bool = False", "", "types"),
]

# ── Flattened completion list ──────────────────────────────────────

def get_all_completions() -> list[str]:
    """Return sorted unique list of all Minescript symbol names for autocomplete."""
    seen = set()
    result = []
    for entry in MINESCRIPT_API + MINESCRIPT_TYPES:
        name = entry.name
        if name not in seen:
            seen.add(name)
            result.append(name)
        # Also provide dotted sub-names  e.g. "BlockPack.read_world"
        if "." in name:
            short = name.split(".")[-1]
            if short not in seen:
                seen.add(short)
                result.append(short)
    result.sort()
    return result


def get_api_entry(name: str) -> APIEntry | None:
    """Lookup an API entry by name (case-insensitive)."""
    low = name.lower()
    for entry in MINESCRIPT_API + MINESCRIPT_TYPES:
        if entry.name.lower() == low:
            return entry
    return None


# ── Category grouping for docs panel ──────────────────────────────

CATEGORIES = [
    ("Output & Commands", "output"),
    ("Player Info", "player"),
    ("Player Movement", "movement"),
    ("Entities", "entities"),
    ("World & Version", "world"),
    ("Blocks", "blocks"),
    ("Jobs & Execution", "jobs"),
    ("Screen & Chat", "screen"),
    ("Events", "events"),
    ("BlockPack / BlockPacker", "blockpack"),
    ("Java Interop", "java"),
    ("Pyjinn", "pyjinn"),
    ("Data Types", "types"),
    ("Commands (in-game)", "commands"),
    # ── MinescriptPlus categories ──────────────────────────────────
    ("MS+ Inventory", "ms_plus_inv"),
    ("MS+ GUI & Screen", "ms_plus_gui"),
    ("MS+ Client & Input", "ms_plus_client"),
    ("MS+ Player", "ms_plus_player"),
    ("MS+ Server", "ms_plus_server"),
    ("MS+ World", "ms_plus_world"),
    ("MS+ Trading", "ms_plus_trading"),
    ("MS+ HUD", "ms_plus_hud"),
    ("MS+ Utility", "ms_plus_util"),
    ("MS+ Events & Keybinds", "ms_plus_events"),
]


def get_entries_by_category(cat_tag: str) -> list[APIEntry]:
    """Return API entries matching a category tag."""
    return [e for e in MINESCRIPT_API + MINESCRIPT_TYPES if e.category == cat_tag]
